# Generated by Django 3.2.5 on 2021-10-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gomoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.TextField()),
                ('number_turns', models.TextField()),
                ('whose_turn', models.TextField()),
                ('difficulty_level', models.TextField(default=None)),
                ('player1_name', models.TextField()),
                ('player1_color', models.TextField()),
                ('player2_name', models.TextField()),
                ('player2_color', models.TextField()),
            ],
        ),
    ]
