# Generated by Django 3.2.5 on 2021-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_remove_stock_macro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('timestamp', models.TextField()),
                ('initial_probabilities', models.TextField()),
                ('transition_probabilities', models.TextField()),
                ('emission_probabilities', models.TextField()),
                ('state_space', models.TextField()),
                ('emission_space', models.TextField()),
            ],
        ),
    ]
